# Generated by Django 4.1.4 on 2023-01-25 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mshop', '0003_milmacurrentorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='milmacurrentorder',
            old_name='location',
            new_name='curlocation',
        ),
    ]
